export const GET_ALL_INGREDIENTS_REQUEST: 'GET_ALL_INGREDIENTS_REQUEST' = "GET_ALL_INGREDIENTS_REQUEST";
export const GET_ALL_INGREDIENTS_FAILED: 'GET_ALL_INGREDIENTS_FAILED'  = "GET_ALL_INGREDIENTS_FAILED";

export const GET_ALL_INGREDIENTS_SUCCESS: 'GET_ALL_INGREDIENTS_SUCCESS'  = "GET_ALL_INGREDIENTS_SUCCESS";
export const SET_DETAIL_INGREDIENTS: 'SET_DETAIL_INGREDIENTS'  = "SET_DETAIL_INGREDIENTS";

export const DELETE_DETAIL_INGREDIENTS: 'DELETE_DETAIL_INGREDIENTS'  = "DELETE_DETAIL_INGREDIENTS";
export const DETAIL_INGREDIENTS_REQUEST: 'DETAIL_INGREDIENTS_REQUEST'  = "DETAIL_INGREDIENTS_REQUEST";
export const DETAIL_INGREDIENTS_FAILED: 'DETAIL_INGREDIENTS_FAILED'  = "DETAIL_INGREDIENTS_FAILED";

export const ADD_ITEM: 'ADD_ITEM'  = "ADD_ITEM";
export const DELETE_ITEM: 'DELETE_ITEM'  = "DELETE_ITEM";

export const DECREASE_ITEM: 'DECREASE_ITEM'  = "DECREASE_ITEM";
export const INCREASE_ITEM: 'INCREASE_ITEM'  = "INCREASE_ITEM";

export const ADD_BUN: 'ADD_BUN'  = "ADD_BUN";
export const CHANGE_ITEM: 'CHANGE_ITEM'  = "CHANGE_ITEM";